# Generated by Django 2.2.2 on 2019-07-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
